FROM node:18-alpine as builder

ENV DISABLE_ESLINT_PLUGIN true

ARG REACT_APP_API_BASE_URL

# ENV REACT_APP_API_BASE_URL https://gsbauth24-uat.dpdpa.osd.co.th//api
# ENV REACT_APP_AUTH_URL https://gsbauth24-uat.dpdpa.osd.co.th/
ENV REACT_APP_AUTH24_BASE_URL=https://id24-demo.osd.co.th
ENV REACT_APP_AUTH_URL=https://id24-demo.osd.co.th
ENV REACT_APP_CLIENT_ID 31633dd9-e3f5-4b6e-8acd-4e03179bfa0a
ENV REACT_APP_CHANNEL_ID=31633dd9-e3f5-4b6e-8acd-4e03179bfa0a
ENV REACT_APP_X_ACCESS_TOKEN=b64be60440c9ed9a6343d456db6ced263ce4ec951d79a7892cdcccca2b47989d
ENV REACT_APP_FEATURE_PUBLIC_CONSENT=true
ENV REACT_APP_USE_AUTH_24=true
ENV REACT_APP_BOOTSTRAP_DATA=false

# ENV REACT_APP_ID24_CLIENT_ID 4855c0d9-d76d-4fd3-97ca-253f1b971e4d

ENV REACT_APP_VERSION 1.0.0
ENV REACT_APP_LANGUAGE TH

WORKDIR /app
COPY package*.json ./
RUN npm install --force 
COPY . .

RUN npm run build

FROM nginx

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get remove -y curl

RUN chgrp -R root /var/cache/nginx && chmod -R 770 /var/cache/nginx
RUN chgrp -R root /var/run && chmod -R 770 /var/run

ADD deploy/default.conf /etc/nginx/conf.d/
RUN mkdir -p /usr/share/nginx/html
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
